# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        kiraxe\AdminCrmBundle\Entity\User:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

        our_db_provider:
            entity:
                class: kiraxe\AdminCrmBundle\Entity\User



    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            logout_on_user_change: true
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login_index
                check_path: login_index
                default_target_path: /admin
                always_use_default_target_path: true
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
            logout:
                path: /logout
                target: /login
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/admin, roles: ROLE_SUPER_ADMIN }