<?php

namespace kiraxe\AdminCrmBundle\Repository;

/**
 * CertificatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificatesRepository extends \Doctrine\ORM\EntityRepository
{
}
