<?php

namespace kiraxe\AdminCrmBundle\Repository;

/**
 * RevenueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevenueRepository extends \Doctrine\ORM\EntityRepository
{
}
