bodytype_index:
    path:     /
    defaults: { _controller: "kiraxeAdminCrmBundle:BodyType:index" }
    methods:  GET

bodytype_show:
    path:     /{id}/show
    defaults: { _controller: "kiraxeAdminCrmBundle:BodyType:show" }
    methods:  GET

bodytype_new:
    path:     /new
    defaults: { _controller: "kiraxeAdminCrmBundle:BodyType:new" }
    methods:  [GET, POST]

bodytype_edit:
    path:     /{id}/edit
    defaults: { _controller: "kiraxeAdminCrmBundle:BodyType:edit" }
    methods:  [GET, POST]

bodytype_delete:
    path:     /{id}/delete
    defaults: { _controller: "kiraxeAdminCrmBundle:BodyType:delete" }
    methods:  DELETE
