сertificates_index:
    path:     /
    defaults: { _controller: "kiraxeAdminCrmBundle:Certificates:index" }
    methods:  GET

сertificates_show:
    path:     /{id}/show
    defaults: { _controller: "kiraxeAdminCrmBundle:Certificates:show" }
    methods:  GET

сertificates_new:
    path:     /new
    defaults: { _controller: "kiraxeAdminCrmBundle:Certificates:new" }
    methods:  [GET, POST]

сertificates_edit:
    path:     /{id}/edit
    defaults: { _controller: "kiraxeAdminCrmBundle:Certificates:edit" }
    methods:  [GET, POST]

сertificates_delete:
    path:     /{id}/delete
    defaults: { _controller: "kiraxeAdminCrmBundle:Certificates:delete" }
    methods:  DELETE