expenses_index:
    path:     /
    defaults: { _controller: "kiraxeAdminCrmBundle:Expenses:index" }
    methods:  GET

expenses_show:
    path:     /{id}/show
    defaults: { _controller: "kiraxeAdminCrmBundle:Expenses:show" }
    methods:  GET

expenses_new:
    path:     /new
    defaults: { _controller: "kiraxeAdminCrmBundle:Expenses:new" }
    methods:  [GET, POST]

expenses_edit:
    path:     /{id}/edit
    defaults: { _controller: "kiraxeAdminCrmBundle:Expenses:edit" }
    methods:  [GET, POST]

expenses_delete:
    path:     /{id}/delete
    defaults: { _controller: "kiraxeAdminCrmBundle:Expenses:delete" }
    methods:  DELETE
