measure_index:
    path:     /
    defaults: { _controller: "kiraxeAdminCrmBundle:Measure:index" }
    methods:  GET

measure_show:
    path:     /{id}/show
    defaults: { _controller: "kiraxeAdminCrmBundle:Measure:show" }
    methods:  GET

measure_new:
    path:     /new
    defaults: { _controller: "kiraxeAdminCrmBundle:Measure:new" }
    methods:  [GET, POST]

measure_edit:
    path:     /{id}/edit
    defaults: { _controller: "kiraxeAdminCrmBundle:Measure:edit" }
    methods:  [GET, POST]

measure_delete:
    path:     /{id}/delete
    defaults: { _controller: "kiraxeAdminCrmBundle:Measure:delete" }
    methods:  DELETE
