user_index:
    path:     /
    defaults: { _controller: "kiraxeAdminCrmBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "kiraxeAdminCrmBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "kiraxeAdminCrmBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "kiraxeAdminCrmBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "kiraxeAdminCrmBundle:User:delete" }
    methods:  DELETE
user_getdump:
    path:     /getdump
    defaults: { _controller: "kiraxeAdminCrmBundle:User:getdump" }
    options:
        expose: true
    methods:  [GET, POST]
